function Truss10InpFileConstr(x)
%
% Construct Abaqus input file for the 10-bar truss optimization problem.
% 
% Syntax
%     Truss10InpFileConstr(#x#);
%
% Description
%     This function creates the input file "Truss10ABAQUS.inp" which is run
%     by Abaqus to analyse the 10-bar truss involved in the optimization
%     procedure of Matlab_Abaqus_10_Bar_Truss package.
%     
% Input parameters
%     #x# ([10 x 1]) is the vector containing the 10 design variables of
%         the 10-bar truss model.
% 
% Output parameters
%     (none)
%
% _________________________________________________________________________
% Abaqus2Matlab - www.abaqus2matlab.com
% Copyright (c) 2019 by George Papazafeiropoulos
%
% If using this toolbox for research or industrial purposes, please cite:
% G. Papazafeiropoulos, M. Muniz-Calvente, E. Martinez-Paneda.
% Abaqus2Matlab: a suitable tool for finite element post-processing.
% Advances in Engineering Software. Vol 105. March 2017. Pages 9-16. (2017) 
% DOI:10.1016/j.advengsoft.2017.01.006
%


% Open output file and start writing
OutputFileName = 'Truss10ABAQUS.inp';
fileID = fopen(OutputFileName,'wt');

fprintf(fileID,' *Heading\n');
fprintf(fileID,' ** Job name: Job-1 Model name: Model-1\n');
fprintf(fileID,' ** Generated by: Abaqus/CAE 6.10-1\n');
fprintf(fileID,' *Preprint, echo=NO, model=NO, history=NO, contact=NO\n');
fprintf(fileID,' **\n');
fprintf(fileID,' ** PARTS\n');
fprintf(fileID,' **\n');
fprintf(fileID,' *Part, name=Part-5\n');
fprintf(fileID,' *End Part\n');
fprintf(fileID,' **  \n');
fprintf(fileID,' **\n');
fprintf(fileID,' ** ASSEMBLY\n');
fprintf(fileID,' **\n');
fprintf(fileID,' *Assembly, name=Assembly\n');
fprintf(fileID,' **  \n');
fprintf(fileID,' *Instance, name=Part-5-1, part=Part-5\n');
fprintf(fileID,' *Node\n');
fprintf(fileID,' 1,	720,	360\n');
fprintf(fileID,' 2,	720,	0\n');
fprintf(fileID,' 3,	360,	360\n');
fprintf(fileID,' 4,	360,	0\n');
fprintf(fileID,' 5,	0,	360\n');
fprintf(fileID,' 6,	0,	0\n');
fprintf(fileID,' *Element, type=FRAME2D\n');
fprintf(fileID,' 1, 5, 3\n');
fprintf(fileID,' 2, 3, 1\n');
fprintf(fileID,' 3, 6, 4\n');
fprintf(fileID,' 4, 4, 2\n');
fprintf(fileID,' 5, 3, 4\n');
fprintf(fileID,' 6, 1, 2\n');
fprintf(fileID,' 7, 5, 4\n');
fprintf(fileID,' 8, 6, 3\n');
fprintf(fileID,' 9, 3, 2\n');
fprintf(fileID,' 10, 4, 1\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#1, internal\n');
fprintf(fileID,'  1,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#2, internal\n');
fprintf(fileID,'  2,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#3, internal\n');
fprintf(fileID,'  3,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#4, internal\n');
fprintf(fileID,'  4,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#5, internal\n');
fprintf(fileID,'  5,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#6, internal\n');
fprintf(fileID,'  6,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#7, internal\n');
fprintf(fileID,'  7,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#8, internal\n');
fprintf(fileID,'  8,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#9, internal\n');
fprintf(fileID,'  9,\n');
fprintf(fileID,' *Elset, elset=_PickedSet2_#10, internal\n');
fprintf(fileID,'  10,\n');
fprintf(fileID,' ******************************************************\n');
fprintf(fileID,' ** Element sections:\n');
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#1, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(1),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#2, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(2),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#3, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(3),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#4, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(4),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#5, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(5),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#6, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(6),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#7, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(7),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#8, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(8),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#9, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(9),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *FRAME Section, elset=_PickedSet2_#10, PINNED\n');
fprintf(fileID,'  %s\n', [num2str(x(10),20),', 1.6E-3, 0, 9E-4']); 
fprintf(fileID,' 0.,0.,-1.\n');
fprintf(fileID,' 1e4, 1e3\n');  
fprintf(fileID,' *End Instance\n');
fprintf(fileID,' *****************************************************\n');
fprintf(fileID,' *Nset, nset=_PickedSet21, internal, instance=Part-5-1\n');
fprintf(fileID,'  2, 4\n');
fprintf(fileID,' *Nset, nset=_PickedSet22, internal, instance=Part-5-1\n');
fprintf(fileID,'  5, 6\n');
fprintf(fileID,' *End Assembly\n');
fprintf(fileID,' ** ----------------------------------------------------------------\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' ** STEP: Step-1\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' *Step, name=Step-1\n');
fprintf(fileID,' *Static\n');
fprintf(fileID,' 1., 1., 1e-05, 1.\n');
fprintf(fileID,' *FILE FORMAT, ASCII\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' ** BOUNDARY CONDITIONS\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' ** Name: BC-1 Type: Displacement/Rotation\n');
fprintf(fileID,' *Boundary\n');
fprintf(fileID,' _PickedSet22, 1, 1\n');
fprintf(fileID,' _PickedSet22, 2, 2\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' ** LOADS\n');
fprintf(fileID,' ** \n');
fprintf(fileID,' ** Name: Load-1   Type: Concentrated force\n');
fprintf(fileID,' *Cload\n');
fprintf(fileID,' _PickedSet21, 2, -100.\n');
fprintf(fileID,' **\n');
fprintf(fileID,' **Write results to *.fil file\n');
fprintf(fileID,' *NODE FILE\n');
fprintf(fileID,' RF, U\n');
fprintf(fileID,' *EL FILE\n');
fprintf(fileID,' SEE, SF\n');
fprintf(fileID,' **\n');
fprintf(fileID,' *End Step\n');

% Close output file
fclose(fileID);